-- Spa POS: appointments + idempotent in-app reminder records
-- Apply this migration in Supabase SQL Editor after reviewing it.
-- This migration does not import or delete existing localStorage appointments.

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  customer_id bigint null references public.customers(id) on delete set null,
  employee_id bigint not null references public.employees(id) on delete restrict,
  appointment_date date not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  title text not null check (length(btrim(title)) > 0),
  notes text null,
  status text not null default 'BOOKED'
    check (status in ('BOOKED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED')),
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint appointments_time_order check (end_time > start_time)
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date, start_time);
create index if not exists appointments_employee_date_idx
  on public.appointments (employee_id, appointment_date, start_time);

create table if not exists public.appointment_reminders (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  reminder_minutes integer not null check (reminder_minutes in (10, 15)),
  created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  notified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint appointment_reminders_once unique (appointment_id, reminder_minutes)
);

create index if not exists appointment_reminders_notified_at_idx
  on public.appointment_reminders (notified_at);

create or replace function public.set_appointment_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_appointments_updated_at on public.appointments;
create trigger trg_appointments_updated_at
before update on public.appointments
for each row execute function public.set_appointment_updated_at();

-- Prevent overlapping active appointments for the same employee, including
-- concurrent requests. Cancelled/completed appointments do not block a slot.
create or replace function public.prevent_appointment_overlap()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status in ('BOOKED', 'CONFIRMED', 'IN_PROGRESS') then
    perform pg_advisory_xact_lock(
      hashtextextended(new.employee_id::text || ':' || new.appointment_date::text, 0)
    );

    if exists (
      select 1
      from public.appointments a
      where a.employee_id = new.employee_id
        and a.appointment_date = new.appointment_date
        and a.status in ('BOOKED', 'CONFIRMED', 'IN_PROGRESS')
        and a.id <> coalesce(new.id, -1)
        and a.start_time < new.end_time
        and a.end_time > new.start_time
    ) then
      raise exception using
        errcode = '23P01',
        message = 'APPOINTMENT_OVERLAP',
        detail = 'Nhân viên đã có lịch hẹn chồng lấn trong khoảng thời gian này.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_appointment_overlap on public.appointments;
create trigger trg_prevent_appointment_overlap
before insert or update of employee_id, appointment_date, start_time, end_time, status
on public.appointments
for each row execute function public.prevent_appointment_overlap();

alter table public.appointments enable row level security;
alter table public.appointment_reminders enable row level security;

drop policy if exists "Active profiles can read appointments" on public.appointments;
create policy "Active profiles can read appointments"
on public.appointments for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
);

drop policy if exists "Active profiles can create appointments" on public.appointments;
create policy "Active profiles can create appointments"
on public.appointments for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
);

drop policy if exists "Active profiles can update appointments" on public.appointments;
create policy "Active profiles can update appointments"
on public.appointments for update to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
);

drop policy if exists "Active profiles can read appointment reminders" on public.appointment_reminders;
create policy "Active profiles can read appointment reminders"
on public.appointment_reminders for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
);

drop policy if exists "Active profiles can create appointment reminders" on public.appointment_reminders;
create policy "Active profiles can create appointment reminders"
on public.appointment_reminders for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.is_active = true
      and p.role_id = any (array[1,2,3]::bigint[])
  )
);

comment on table public.appointments is
  'Spa POS appointments. Frontend display statuses are mapped from these backend status codes.';
comment on table public.appointment_reminders is
  'Idempotency ledger for 15-minute and 10-minute in-app appointment reminders.';
