-- Phase 1.1 - Core POS backend (safe additive migration)
-- Review before running in Supabase SQL Editor.
-- This migration does not recreate or delete existing business tables/data.

begin;

-- 1) Allocate order-level discount to invoice lines
alter table public.invoice_items
  add column if not exists allocated_order_discount_amount numeric not null default 0;

alter table public.invoice_items
  drop constraint if exists invoice_items_allocated_order_discount_check;

alter table public.invoice_items
  add constraint invoice_items_allocated_order_discount_check
  check (allocated_order_discount_amount >= 0);

-- 2) Funds
create table if not exists public.funds (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  fund_type text not null,
  opening_balance numeric not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint funds_opening_balance_check check (opening_balance >= 0),
  constraint funds_type_check check (
    fund_type in ('CASH','BANK','E_WALLET','CARD_POS')
  )
);

-- 3) Shifts
create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  opened_by uuid not null references auth.users(id),
  opened_at timestamptz not null default now(),
  opening_cash numeric not null default 0,
  closed_by uuid references auth.users(id),
  closed_at timestamptz,
  expected_cash numeric not null default 0,
  actual_cash numeric,
  difference numeric,
  status text not null default 'OPEN',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shifts_opening_cash_check check (opening_cash >= 0),
  constraint shifts_expected_cash_check check (expected_cash >= 0),
  constraint shifts_actual_cash_check check (actual_cash is null or actual_cash >= 0),
  constraint shifts_status_check check (status in ('OPEN','CLOSED','CANCELLED'))
);

create unique index if not exists shifts_one_open_per_user_idx
  on public.shifts (opened_by)
  where status = 'OPEN';

-- 4) Link payments to collection shift
alter table public.payments
  add column if not exists shift_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'payments_shift_id_fkey'
      and conrelid = 'public.payments'::regclass
  ) then
    alter table public.payments
      add constraint payments_shift_id_fkey
      foreign key (shift_id) references public.shifts(id);
  end if;
end $$;

create index if not exists payments_shift_id_idx
  on public.payments (shift_id);

-- 5) Debts
create table if not exists public.debts (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id),
  customer_id bigint not null references public.customers(id),
  original_amount numeric not null,
  paid_amount numeric not null default 0,
  remaining_amount numeric not null,
  due_date date not null,
  status text not null default 'OPEN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint debts_original_amount_check check (original_amount >= 0),
  constraint debts_paid_amount_check check (paid_amount >= 0),
  constraint debts_remaining_amount_check check (remaining_amount >= 0),
  constraint debts_status_check check (status in ('OPEN','PARTIAL','PAID','CANCELLED')),
  constraint debts_amount_consistency_check check (
    remaining_amount = greatest(original_amount - paid_amount, 0)
  )
);

create unique index if not exists debts_one_active_per_invoice_idx
  on public.debts (invoice_id)
  where status in ('OPEN','PARTIAL');

create index if not exists debts_customer_id_idx on public.debts (customer_id);
create index if not exists debts_due_date_idx on public.debts (due_date);

-- 6) Debt collections
create table if not exists public.debt_collections (
  id bigint generated by default as identity primary key,
  debt_id bigint not null references public.debts(id),
  payment_id bigint not null references public.payments(id),
  shift_id bigint not null references public.shifts(id),
  amount numeric not null,
  collection_date timestamptz not null default now(),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint debt_collections_amount_check check (amount > 0)
);

create index if not exists debt_collections_debt_id_idx on public.debt_collections (debt_id);
create index if not exists debt_collections_shift_id_idx on public.debt_collections (shift_id);
create index if not exists debt_collections_collection_date_idx on public.debt_collections (collection_date);

-- 7) Cashbook
create table if not exists public.cashbook_transactions (
  id bigint generated by default as identity primary key,
  fund_id bigint not null references public.funds(id),
  shift_id bigint references public.shifts(id),
  transaction_type text not null,
  category text not null,
  direction text not null,
  amount numeric not null,
  payment_id bigint references public.payments(id),
  reference_type text,
  reference_id bigint,
  txn_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  note text,
  created_at timestamptz not null default now(),
  constraint cashbook_amount_check check (amount > 0),
  constraint cashbook_direction_check check (direction in ('IN','OUT')),
  constraint cashbook_type_check check (
    transaction_type in (
      'SALE','DEBT_COLLECTION','RETURN_REFUND','EXPENSE',
      'OPENING_BALANCE','ADJUSTMENT','OTHER'
    )
  )
);

create index if not exists cashbook_transactions_shift_id_idx
  on public.cashbook_transactions (shift_id);
create index if not exists cashbook_transactions_fund_id_idx
  on public.cashbook_transactions (fund_id);
create index if not exists cashbook_transactions_txn_at_idx
  on public.cashbook_transactions (txn_at);
create index if not exists cashbook_transactions_reference_idx
  on public.cashbook_transactions (reference_type, reference_id);

-- 8) updated_at helper for new tables
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists funds_set_updated_at on public.funds;
create trigger funds_set_updated_at
before update on public.funds
for each row execute function public.set_updated_at();

drop trigger if exists shifts_set_updated_at on public.shifts;
create trigger shifts_set_updated_at
before update on public.shifts
for each row execute function public.set_updated_at();

drop trigger if exists debts_set_updated_at on public.debts;
create trigger debts_set_updated_at
before update on public.debts
for each row execute function public.set_updated_at();

-- 9) RLS: read-only baseline for authenticated users.
-- No write policies yet; API/RPC authorization will be finalized separately.
alter table public.funds enable row level security;
alter table public.shifts enable row level security;
alter table public.debts enable row level security;
alter table public.debt_collections enable row level security;
alter table public.cashbook_transactions enable row level security;

drop policy if exists "Authenticated users can read funds" on public.funds;
create policy "Authenticated users can read funds"
  on public.funds for select to authenticated using (true);

drop policy if exists "Authenticated users can read shifts" on public.shifts;
create policy "Authenticated users can read shifts"
  on public.shifts for select to authenticated using (true);

drop policy if exists "Authenticated users can read debts" on public.debts;
create policy "Authenticated users can read debts"
  on public.debts for select to authenticated using (true);

drop policy if exists "Authenticated users can read debt collections" on public.debt_collections;
create policy "Authenticated users can read debt collections"
  on public.debt_collections for select to authenticated using (true);

drop policy if exists "Authenticated users can read cashbook transactions" on public.cashbook_transactions;
create policy "Authenticated users can read cashbook transactions"
  on public.cashbook_transactions for select to authenticated using (true);

commit;
